Language:
  Abilities:
    Spirit:
      Agility:
        Description: This ability offers you 2 modes of mobility. The first being
          the ability to dash forward very quickly. The second being the ability to
          soar through the skies as if gravity is non-existant.
        Instructions: 'Left-Click: Dash ⏐ Hold shift: Soar'
      Possess:
        Description: A very ancient ability of Spirits is the ability to jump inside
          the body of a human. As a Spirit, you'll be able to possess a human for
          a short amount of time and do harm. While this ability is active, both the
          Spirit and the target will be motionless.
        Instructions: Hold shift and look at a human.
      Phase:
        Description: This advanced combo allows a Spirit to dematerialize into a state
          where they can walk through walls and fly around a certain radius. They
          are able to do this because of their unqiue molecular makeup not seen in
          any other being!
        Instructions: 'Vanish (Left-click 2x) > Possess (Tap-shift) > Vanish (Left-click)
          ⏐ To Exit: Vanish (Tap-shift)'
      Vanish:
        Description: Spirits are often seen disappearing into thin air and then reappearing
          somewhere different. With this ability, you can harness that power as well!
          However, there is a certain duration you are able to vanish for an a radius
          of how far away from your original location you're allowed to get!
        Instructions: 'Hold shift: Disappear ⏐ Release shift: Reappear'
    LightSpirit:
      Alleviate:
        Description: The healing ability for LightSpirits, this allows you to heal
          yourself and others! When healing, whoever is being healed will be removed
          of ANY negative potion effects aswell as recieve regeneration for a period
          of time.
        Instructions: 'Hold Shift while lookat at a target: Heal them ⏐ Hold Shift
          while looking away: Heal yourself.'
      Rejuvenate:
        Description: After executing the combo sequence, you will mark the ground
          with positively charged spiritual energy for a duration of time. Entities
          can come to this location to heal themselves, but dark creatures must beware!
        Instructions: Alleviate (Shift down) > Alleviate (Right-Click block) > Alleviate
          (Release shift)
      Orb:
        Description: Plant an orb of positive energy on the ground which awaits for
          oncoming entities. If the orb detects something moving past it, it'll expand
          and harm anyone in its wake! More features to come...
        Instructions: Hold shift until you see particles. Release shift while looking
          at an area nearby on the ground to plant it there.
      Shelter:
        Description: A very useful tactic when group battling, a light spirit can
          temporarily shield a friend or even a foe from incoming enemies. Additionally,
          they have the options to shield themselves!
        Instructions: 'Left click: Shield others ⏐ Hold shift: Shield yourself.'
    DarkSpirit:
      Intoxicate:
        Description: Sacrifice some of your energy to pour a bit of chaos into the
          souls of your nearby enemies by taking away their positive potion effects
          and adding negative ones. Then watch as it destroys them from the inside
          out! The great spirit Vaatu was known to have this influence over other
          unbalanced Spirits.
        Instructions: Hold shift
      Infest:
        Description: After executing the combo sequence, you will mark the ground
          with negatively charged spiritual energy for a duration of time. Monsters
          can come to this location for strength, but any other entities must beware!
        Instructions: Intoxicate (Shift down) > Intoxicate (Right-Click block) > Intoxicate
          (Release shift)
      Shackle:
        Description: With this technique a DarkSpirit is able to temporarily trap
          an anyone dead in their tracks, even if you can't see them! Useful for a
          quick get away...
        Instructions: Left click
      Strike:
        Description: The most basic ability of an aggressive, unbalanced Spirit is
          to rush towards their enemy and try to bite them in 1 swift motion. When
          you activate this ability, you'll see your target zone. If your target zone
          gets in range of another entity, you'll be rushed over to them an deal damage.
        Instructions: Left-Click to trigger target spectacle
    Water:
      Purify:
        Description: A rare technique practice amongst waterbenders is the ability
          to influence a Spirits nature towards either the darkness or the light.
          Using this ability, you can influence a DarkSpirit to be peaceful and guide
          them towards the light.
        Instructions: Hold shift while looking at an entity
      Corrupt:
        Description: A rare technique practice amongst waterbenders is the ability
          to influence a Spirits nature towards either the darkness or the light.
          Using this ability, you can influence a LightSpirit to be chaotic and follow
          the will of the great DarkSpirit, Vatuu.
        Instructions: Hold shift while looking at an entity
Abilities:
  Spirits:
    Neutral:
      Agility:
        Enabled: true
        Dash:
          Cooldown: 2000
          Distance: 3
        Soar:
          Cooldown: 4500
          Duration: 1000
          Speed: 0.8
      Possess:
        Enabled: true
        Cooldown: 5000
        Radius: 5
        Damage: 5
        Duration: 2000
        DisablePunching: true
      Vanish:
        Enabled: true
        Cooldown: 7000
        Duration: 10000
        ChargeTime: 1500
        Range: 20
        Radius: 10
        ParticleFrequency: 5
        RemoveFire: true
        DivideRange:
          Enabled: true
          HealthRequired: 10
          DivideFactor: 2
      Combo:
        Phase:
          Enabled: true
          Cooldown: 20000
          Duration: 10000
          Range: 10
          MinHealth: 6
          Vanish:
            ApplyCooldown: true
            Cooldown: 20000
    LightSpirit:
      Alleviate:
        Enabled: true
        Others:
          Cooldown: 5000
          Range: 5
          PotionInterval: 2000
          HealInterval: 5000
          SelfDamage: 6
          ParticleColor (Has to be 6 characters): FFFFFF
        Self:
          Cooldown: 5000
          ChargeTime: 2000
          HealDuration: 1.5
          NightVisionDuration: 1.5
          RemoveNegativePotionEffects: true
          ParticleColor (Has to be 6 characters): FFFFFF
      Orb:
        Enabled: true
        Cooldown: 10000
        ChargeTime: 2000
        Duration: 30000
        Damage: 3
        PlaceRange: 20
        DetonateRange: 3
        EffectRange: 5
        BlindnessDuration: 120
        NauseaDuration: 300
        PotionPower: 2
        RequireGround: true
      Shelter:
        Enabled: true
        RemoveOnDamage: true
        Duration: 7000
        Range: 20
        Others:
          ClickDelay: 2000
          Cooldown: 10000
          ShieldSize: 5
          KnockbackPower: 1
        Self:
          Cooldown: 10000
          ShieldSize: 4
          KnockbackPower: 1
        RemoveIfFarAway:
          Enabled: true
          Distance: 5
      Combo:
        Rejuvenate:
          Enabled: true
          Cooldown: 15000
          Duration: 10000
          Radius: 5
          Damage: 1
          EffectInterval: 10
          HurtDarkSpirits: true
          HurtMonsters: true
    DarkSpirit:
      Intoxicate:
        Enabled: true
        Cooldown: 5000
        Radius: 5
        PotionInterval: 2000
        HarmInterval: 5000
        SelfDamage: 4
        ParticleColor (Has to be 6 characters): BD0000
      Shackle:
        Enabled: true
        Cooldown: 5000
        Duration: 2500
        Range: 20
        Radius: 2
      Strike:
        Enabled: true
        Cooldown: 4000
        Range: 5
        Damage: 3
      Combo:
        Infest:
          Enabled: true
          Cooldown: 15000
          Duration: 10000
          Radius: 8
          EffectInterval: 10
          Damage: 1
          DamageEntities: true
          HealDarkSpirits: true
    Water:
      Purify:
        SwitchPercent: 0.33
        Enabled: true
        Cooldown: 5000
        Duration: 6000
        Range: 20
        SetElement: true
      Corrupt:
        SwitchPercent: 0.33
        Damage: 7
        Enabled: true
        Cooldown: 5000
        Duration: 6000
        Range: 20
        SetElement: true
